import type { Locale } from "@/lib/portfolio"

type Entry = { de: string; en: string }

export const copy: Record<string, Entry> = {
  // Login
  "login.badge": { de: "PickTheBank Kundenportal", en: "PickTheBank customer portal" },
  "login.title": { de: "Kundenlogin", en: "Customer login" },
  "login.subtitle": {
    de: "Einlagen, Zinsgutschriften und Portfolio-Reports einsehen – alle Anlagen bei unseren Partnerbanken an einem Ort.",
    en: "Review deposits, interest credits and portfolio reports – every holding with our partner banks in one place.",
  },
  "login.email": { de: "E-Mail-Adresse", en: "Email address" },
  "login.emailPlaceholder": { de: "ihre@email.de", en: "your@email.com" },
  "login.password": { de: "Passwort", en: "Password" },
  "login.showPassword": { de: "Passwort anzeigen", en: "Show password" },
  "login.hidePassword": { de: "Passwort verbergen", en: "Hide password" },
  "login.remember": { de: "Angemeldet bleiben", en: "Keep me signed in" },
  "login.forgot": { de: "Passwort vergessen?", en: "Forgot password?" },
  "login.submit": { de: "Anmelden", en: "Log in" },
  "login.submitting": { de: "Wird geprüft …", en: "Signing in …" },
  "login.demoButton": { de: "Demo-Zugang einsetzen", en: "Use demo access" },
  "login.demoHint": {
    de: "Prototyp: Mit dem Demo-Zugang oder einer beliebigen gültigen E-Mail (Passwort ab 8 Zeichen) öffnet sich das Portal mit Beispieldaten.",
    en: "Prototype: the demo access – or any valid email with a password of at least 8 characters – opens the portal with sample data.",
  },
  "login.noAccount": { de: "Noch kein Zugang?", en: "No account yet?" },
  "login.openAccount": { de: "Anlagekonto eröffnen", en: "Open a savings account" },
  "login.backHome": { de: "Zurück zur Website", en: "Back to the website" },
  "login.errorEmail": { de: "Bitte geben Sie eine gültige E-Mail-Adresse ein.", en: "Please enter a valid email address." },
  "login.errorPassword": {
    de: "Das Passwort muss mindestens 8 Zeichen haben.",
    en: "The password must contain at least 8 characters.",
  },
  "login.resetTitle": { de: "Passwort zurücksetzen", en: "Reset password" },
  "login.resetText": {
    de: "Wir senden einen Link zum Zurücksetzen an Ihre hinterlegte E-Mail-Adresse.",
    en: "We will send a reset link to the email address on file.",
  },
  "login.resetSubmit": { de: "Link anfordern", en: "Request link" },
  "login.resetSent": {
    de: "Wenn ein Konto existiert, ist der Link unterwegs. Bitte prüfen Sie Ihr Postfach.",
    en: "If an account exists the link is on its way. Please check your inbox.",
  },
  "login.resetBack": { de: "Zurück zur Anmeldung", en: "Back to sign in" },
  "login.uspTitle": {
    de: "Ein Portal für jede Einlage bei unseren Partnerbanken.",
    en: "One portal for every deposit you hold with our partner banks.",
  },
  "login.usp1": {
    de: "Portfolio-Report mit Bestand, Zinsertrag und Laufzeiten – jederzeit als PDF.",
    en: "Portfolio report with holdings, interest income and terms – available as a PDF at any time.",
  },
  "login.usp2": {
    de: "Fälligkeiten und Wiederanlage im Blick, bevor eine Anlage ausläuft.",
    en: "Maturities and reinvestments in view before a deposit runs out.",
  },
  "login.usp3": {
    de: "Verträge, Kontoauszüge und Steuerbescheinigungen gebündelt im Dokumentenbereich.",
    en: "Contracts, statements and tax certificates bundled in the document area.",
  },
  "login.security": {
    de: "Starke Kundenauthentifizierung · Einlagensicherung im EWR bis 100.000 €",
    en: "Strong customer authentication · EEA deposit guarantee up to €100,000",
  },

  // Shell
  "nav.dashboard": { de: "Übersicht", en: "Dashboard" },
  "nav.holdings": { de: "Anlagen", en: "Holdings" },
  "nav.transactions": { de: "Transaktionen", en: "Transactions" },
  "nav.documents": { de: "Dokumente", en: "Documents" },
  "nav.banks": { de: "Partnerbanken", en: "Partner banks" },
  "nav.profile": { de: "Profil", en: "Profile" },
  "nav.support": { de: "Support", en: "Support" },
  "shell.portal": { de: "Kundenportal", en: "Customer portal" },
  "shell.loggedInAs": { de: "ANGEMELDET ALS", en: "SIGNED IN AS" },
  "shell.customerNo": { de: "Kunde", en: "Client" },
  "shell.logout": { de: "Abmelden", en: "Log out" },
  "shell.search": { de: "Suchen …", en: "Search …" },
  "shell.notifications": { de: "Benachrichtigungen", en: "Notifications" },
  "shell.menu": { de: "Menü", en: "Menu" },
  "shell.demoBadge": { de: "Demo-Daten", en: "Demo data" },
  "shell.loading": { de: "Portal wird geladen …", en: "Loading portal …" },
  "shell.website": { de: "Zur Website", en: "To the website" },

  // Report / dashboard
  "report.title": { de: "Portfolio-Report", en: "Investment portfolio report" },
  "report.subtitle": { de: "Auswertung Ihrer Einlagen", en: "Portfolio performance analysis" },
  "report.generated": { de: "Erstellt", en: "Generated" },
  "report.print": { de: "Report drucken", en: "Print report" },
  "report.portfolioValue": { de: "Portfoliowert", en: "Portfolio value" },
  "report.email": { de: "E-Mail", en: "Email" },
  "report.phone": { de: "Telefon", en: "Phone" },
  "report.address": { de: "Adresse", en: "Address" },
  "report.customerNo": { de: "Kundennr.", en: "Client #" },
  "kpi.invested": { de: "Angelegtes Kapital", en: "Total purchase value" },
  "kpi.value": { de: "Aktueller Wert", en: "Current value" },
  "kpi.profit": { de: "Zinsertrag bisher", en: "Total profit" },
  "kpi.count": { de: "Anlagen", en: "Total holdings" },
  "kpi.euro": { de: "Euro", en: "Euro" },
  "kpi.banks": { de: "Partnerbanken", en: "Companies" },
  "summary.title": { de: "Portfolio-Zusammenfassung", en: "Portfolio summary" },
  "summary.invested": { de: "Angelegtes Kapital", en: "Total investment" },
  "summary.value": { de: "Aktueller Wert", en: "Current value" },
  "summary.profit": { de: "Zinsertrag bisher", en: "Net profit" },
  "summary.expected": { de: "Zinsertrag bei Laufzeitende", en: "Interest at maturity" },
  "summary.rate": { de: "Ø Zinssatz", en: "Average rate" },
  "details.title": { de: "Report-Details", en: "Report details" },
  "details.date": { de: "Report-Datum", en: "Report date" },
  "details.holdings": { de: "Anlagen", en: "Total holdings" },
  "details.currency": { de: "Währung", en: "Currency" },
  "details.basis": {
    de: "Berechnung: anteilige Zinsen pro Laufzeitmonat",
    en: "Basis: interest accrued pro rata per month of term",
  },
  "chart.title": { de: "Portfolioentwicklung", en: "Portfolio development" },
  "chart.subtitle": { de: "Letzte 12 Monate", en: "Last 12 months" },
  "chart.value": { de: "Portfoliowert", en: "Portfolio value" },
  "allocation.title": { de: "Verteilung nach Bank", en: "Allocation by bank" },
  "allocation.subtitle": { de: "Anteil am Portfoliowert", en: "Share of portfolio value" },
  "activity.title": { de: "Aktivitäten", en: "Activity" },
  "maturities.title": { de: "Nächste Fälligkeiten", en: "Upcoming maturities" },
  "maturities.in": { de: "in", en: "in" },
  "maturities.months": { de: "Monaten", en: "months" },
  "maturities.due": { de: "fällig", en: "due" },
  "common.viewAll": { de: "Alle ansehen", en: "View all" },

  // Views
  "holdings.title": { de: "Anlagen", en: "Holdings" },
  "holdings.subtitle": {
    de: "Alle Festgeld- und Flex-Einlagen bei unseren Partnerbanken.",
    en: "Every fixed-term and flexible deposit with our partner banks.",
  },
  "transactions.title": { de: "Transaktionen", en: "Transactions" },
  "transactions.subtitle": {
    de: "Einzahlungen, Zinsgutschriften und Rückzahlungen.",
    en: "Deposits, interest credits and repayments.",
  },
  "documents.title": { de: "Dokumente", en: "Documents" },
  "documents.subtitle": {
    de: "Verträge, Reports und Steuerbescheinigungen als PDF.",
    en: "Contracts, reports and tax certificates as PDF.",
  },
  "banks.title": { de: "Partnerbanken", en: "Partner banks" },
  "banks.subtitle": {
    de: "Aktuelle Konditionen der Banken, über die Sie anlegen können.",
    en: "Current terms of the banks you can invest with.",
  },
  "banks.rate": { de: "Zinssatz p. a.", en: "Rate p.a." },
  "banks.term": { de: "Laufzeit", en: "Term" },
  "banks.invest": { de: "Anlage anfragen", en: "Request deposit" },
  "profile.title": { de: "Profil & Sicherheit", en: "Profile & security" },
  "profile.subtitle": {
    de: "Ihre Stammdaten und die Sicherheitseinstellungen des Zugangs.",
    en: "Your master data and the security settings of this account.",
  },
  "profile.name": { de: "Name", en: "Name" },
  "profile.advisor": { de: "Ihre Betreuung", en: "Your adviser" },
  "profile.security": { de: "Sicherheit", en: "Security" },
  "profile.twoFactor": { de: "Zwei-Faktor-Authentisierung aktiv", en: "Two-factor authentication active" },
  "profile.lastLogin": { de: "Letzte Anmeldung", en: "Last sign-in" },
  "profile.changePassword": { de: "Passwort ändern", en: "Change password" },
  "profile.editHint": {
    de: "Stammdaten ändert Ihre Betreuung nach Legitimationsprüfung – eine Anfrage genügt.",
    en: "Master data is changed by your adviser after an identity check – a short request is enough.",
  },
  "profile.editRequest": { de: "Änderung anfragen", en: "Request a change" },
  "support.title": { de: "Support", en: "Support" },
  "support.subtitle": {
    de: "Ihr Team von PickTheBank ist werktags von 9 bis 17 Uhr erreichbar.",
    en: "Your PickTheBank team is available on weekdays from 9am to 5pm.",
  },
  "support.call": { de: "Rückruf vereinbaren", en: "Book a callback" },
  "support.email": { de: "E-Mail schreiben", en: "Send an email" },
  "support.advisor": { de: "Beratungstermin buchen", en: "Book an advisory call" },
  "support.responseTime": { de: "Antwort in der Regel unter 4 Stunden", en: "Typical reply time under 4 hours" },

  // Table columns
  "col.bank": { de: "Bank", en: "Company" },
  "col.product": { de: "Produkt", en: "Symbol" },
  "col.amount": { de: "Anlagebetrag", en: "Investment amount" },
  "col.rate": { de: "Zinssatz", en: "Interest rate" },
  "col.term": { de: "Laufzeit", en: "Term" },
  "col.value": { de: "Aktueller Wert", en: "Current value" },
  "col.profit": { de: "Zinsertrag", en: "Profit" },
  "col.status": { de: "Status", en: "Status" },
  "col.maturity": { de: "Fälligkeit", en: "Maturity" },
  "col.date": { de: "Datum", en: "Date" },
  "col.kind": { de: "Vorgang", en: "Type" },
  "col.document": { de: "Dokument", en: "Document" },
  "col.country": { de: "Land", en: "Country" },
  "col.months": { de: "Monate", en: "months" },
  "table.empty": { de: "Keine Einträge gefunden.", en: "No entries found." },
  "table.download": { de: "PDF", en: "PDF" },
}

export function createT(locale: Locale) {
  return (key: string) => copy[key]?.[locale] ?? key
}
